### ISSUE TITLE
Fix margins in "Portfolio"

### ISSUE THREAD

**Issue by shubhammalhotra1708** [TEJASVISJAIN/portfolio-website#4]
When navigating to "Portfolio" from the top navbar, the section doesn't fir properly in the window frame. I have to scroll down for the entire postman box which is abruptly cut out at the bottom. There's a lot of margin after the postman heading, so maybe we could utilize that better

**Comment by shubhammalhotra1708** [comment]
<img width="1512" alt="image" src="https://github.com/TEJASVISJAIN/portfolio-website/assets/72342801/c3bc7cf1-7c0e-4d14-a5e8-6ebdc79302e2">

**Comment by TEJASVISJAIN** [comment]
@shubhammalhotra1708 fixed the issue, thank you fo reporting it
