### ISSUE TITLE
Margin in "Experience" is inconsistent

### ISSUE THREAD

**Issue by shubhammalhotra1708** [TEJASVISJAIN/portfolio-website#5]
I believe margins should be same across similar layout sections. For example - About, Postman and Experience should have their sections headings at the same height, which they currently aren't. Similarly, some slight tweaks could be made to align Portfolio and Contact, just to make it more pleasing to the visitor's eye.

**Comment by TEJASVISJAIN** [comment]
@shubhammalhotra1708 fixed background in portfolio to make it consistent, handled a couple margin and padding issues aswell
